name: Example Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::870189690984:role/GitHubActionsProjectARole'
          aws-region: 'ap-northeast-1'

      - run: aws s3 ls s3://xils-silver-cf-template

      - name: Run a simple script
        run: echo "Hello, GitHub Actions!"
